#################################################################################
#                                                                               #
#   This is a private configuration file for lazygit. Any config in this file   #
#    will only be saved locally and will not be pushed to the upstream repo.    #
#                                                                               #
#       Make sure to run `git update-index --skip-worktree` on this file        #
#                   to prevent changes from being tracked.                      #
#                                                                               #
#       NOTE: Any top level YAML element in this file will overwrite the        #
#         corresponding YAML element in the parent lazygit config file.         #
#                                                                               #
#################################################################################

